### ISSUE TITLE
Doesn't work with YAML

### ISSUE THREAD

**Issue by Dunedan** [jstewmon/check-swagger#2]
When trying to run this with a YAML-template (e.g. the example Petstore API YAML file: http://petstore.swagger.io/v2/swagger.yaml), all I get is the following error message:
`expected string or buffer`

JSON works fine.

**Comment by jstewmon** [comment]
This is related to Julian/jsonschema#286.

The Swagger Specification [Data Types] are defined by a JSON Schema . JSON object keys must be strings, but the yaml version of the petstore spec defines the `responses` keys as integers, which leads to a an error when processing the a spec that was deserialized from invalid JSON.

A potential workaround for check-swagger would be to round-trip the yaml-parsed swagger file through `json.dumps` and `json.loads`, which will coerce the integer keys to strings.

I think this is a reasonable thing for check-swagger to do, so I'm going to go ahead with it as a workaround.

[Data Types]: http://swagger.io/specification/#data-types-12
